name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci 
        working-directory: '${{ github.workspace }}/src'
        run: npm ci
    - name: build 
        working-directory: '${{ github.workspace }}/src'
        run: npm run build
    - uses: lauchacarro/Azure-Storage-Action@master
      with:
        enabled-static-website: 'true'
        folder: '${{ github.workspace }}/src/dist'
        index-document: 'index.html'
        connection-string: ${{ secrets.azure_storage_connection_string }}